### ISSUE TITLE
PaypalMobile class not found

### ISSUE THREAD

**Issue by kapil019** [romk1n/MyCordovaShop#2]
Hi,
I am trying "MyCordovaShop", and runing my code in ripple emulator. And i am geting error.

This is not executing in android. I have created apk file, and installed in phone. and i am geting error.

03-05 16:16:51.665: D/PluginManager(13867): exec() call to unknown plugin: PayPalMobile
03-05 16:16:51.675: D/CordovaLog(13867): file:///android_asset/www/plugins/com.paypal.cordova.mobilesdk/www/cdv-plugin-paypal-mobile-sdk.js: Line 41 : Class not found
03-05 16:16:51.675: I/chromium(13867): [INFO:CONSOLE(41)] "Class not found", source: file:///android_asset/www/plugins/com.paypal.cordova.mobilesdk/www/cdv-plugin-paypal-mobile-sdk.js (41)

**Comment by romk1n** [comment]
@kapil019 please check this issue and see if the same can be applied to your problem ? https://github.com/romk1n/MyCordovaShop/issues/1

**Comment by kapil019** [comment]
This issue has been fixed, we were runing code on a ripple emulator, that was not working like a simulator. But now i am running app on android and ios. This is working fine for both.
